### PR TITLE
Configured template localization

### PR DESCRIPTION
**Pull request by katporks**
From the acceptance criteria in the [Originating issue](https://github.com/hotosm/website/issues/14):
Template strings are added throughout the codebase where text content is present.
The make messages command is successfully integrated into Docker and can be run without errors.
Updated .po files are generated when make messages is run.

TODO: Will add documentation on how to correctly enable translation on a template string

### CODE REVIEW

**Comment by katporks** [comment]
@spwoodcock @dakotabenjamin hi! I'm hoping to get insight on the following error when deploying to test within the HOT's reusable pytest GH workflow:

```
Downloading envsubst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100 2357k  100 2357k    0     0  4054k      0 --:--:-- --:--:-- --:--:-- 4054k
Substituting variables from  --> .env
/home/runner/work/_temp/b0fb54d6-9df1-49ff-ac58-527e6fa22141.sh: line 8: : No such file or directory
Error: Process completed with exit code 1.
```

**Comment by spwoodcock** [comment]
Oh that might be my fault! Thanks for flagging!

I am back tomorrow and will fix this - a minor tweak to the workflow. 

Until then you can just pin the specific version of gh-workflows. Change `@main` to be a specific tag like `@1.4.3`.

I wouldn't recommend ever pinning to `main` as the latest version will be pulled & may cause breaking changes in the future 👍

**Comment by katporks** [comment]
> Oh that might be my fault! Thanks for flagging!
> 
> I am back tomorrow and will fix this - a minor tweak to the workflow.
> 
> Until then you can just pin the specific version of gh-workflows. Change `@main` to be a specific tag like `@1.4.3`.
> 
> I wouldn't recommend ever pinning to `main` as the latest version will be pulled & may cause breaking changes in the future 👍

@spwoodcock thanks for checking, I'll take this PR out of draft state then! Hope you're having a good weekend 👍🏼

**Comment by spwoodcock** [comment]
I fixed the workflow - it was a minor update that broke the .env file generation.

Going forward I would recommend pinning like this:

```yaml
jobs:
  pytest:
    uses: hotosm/gh-workflows/.github/workflows/test_compose.yml@1.4.8
    with:
```

otherwise breakage in the future is likely 👍

**Pull request merged**
